server:
  host: ""
  port: 8080

security:
  auth:
    jwt:
      secret: ${JWT_SECRET}
      issuer: auth-provider-ms
      ttlMinutes: 60
    cookie:
      name: token
      domain: ""
      secure: false
      httpOnly: true
      sameSite: Strict
    login:
      email: ${ALLOWED_EMAILS}
    oauth2:
      providers:
        google:
          clientID: ${GOOGLE_CLIENT_ID}
          clientSecret: ${GOOGLE_CLIENT_SECRET}
          authURL: https://accounts.google.com/o/oauth2/auth
          tokenURL: https://oauth2.googleapis.com/token
          redirectURL: http://localhost:8080/login/oauth2/code/google
          scopes:
            - https://www.googleapis.com/auth/userinfo.email
            - https://www.googleapis.com/auth/userinfo.profile
